services:
  mongo-blog:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-blog
      - MONGO_INITDB_ROOT_PASSWORD=mongo-password
